# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a5578cdb0b3dc73349e3750441eafe57"
name = "Urban Chat"
handle = "urban-chat-1"
application_url = "https://challenged-junction-utilization-hereby.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testf5363.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://challenged-junction-utilization-hereby.trycloudflare.com/auth/callback",
  "https://challenged-junction-utilization-hereby.trycloudflare.com/auth/shopify/callback",
  "https://challenged-junction-utilization-hereby.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
